// Пробіли між цифрами не допускаються
integer = @{ ASCII_DIGIT+ }

atom = _{ integer }

bin_op = _{ add | subtract | multiply | divide }
	add = { "+" }
	subtract = { "-" }
	multiply = { "*" }
	divide = { "/" }

expr = { atom ~ (bin_op ~ atom)* }

WHITESPACE = _{ " " }

// Ми не можемо мати SOI та EOI безпосередньо на expr, тому що він використовується
// рекурсивно (наприклад, у круглих дужках)
equation = _{ SOI ~ expr ~ EOI }